// Auto-generated by dev-tools/generate-types.js. DO NOT EDIT DIRECTLY.

export const GRAPH_LAYOUT_LIST: readonly string[] = [
  "fcose",
  "cose",
  "dagre",
  "breadthfirst",
  "concentric",
  "circle",
  "grid"
];

export const GRAPH_LAYOUT_ICON_MAP: { [K in (typeof GRAPH_LAYOUT_LIST)[number]]: any } = {
  "fcose": { icon: "⚡", label: "Force (fCoSE)" },
  "cose": { icon: "🧲", label: "CoSE" },
  "dagre": { icon: "🔀", label: "Dagre (DAG)" },
  "breadthfirst": { icon: "🌲", label: "Tree (BFS)" },
  "concentric": { icon: "🎯", label: "Concentric" },
  "circle": { icon: "⭕", label: "Circle" },
  "grid": { icon: "▦", label: "Grid" },
} as const;

export type GraphLayout = (typeof GRAPH_LAYOUT_LIST)[number];

export function isGraphLayout(value: unknown): value is GraphLayout {
  return typeof value === "string" && GRAPH_LAYOUT_LIST.includes(value);
}

export function getGraphLayout(value: unknown): GraphLayout | undefined {
  if (typeof value === "string" && GRAPH_LAYOUT_LIST.includes(value)) {
    return value as GraphLayout;
  }
  return undefined;
}
