// Auto-generated by dev-tools/generate-types.js. DO NOT EDIT DIRECTLY.

export const DISPLAY_LEVEL_LIST: readonly string[] = [
  "all",
  "component",
  "class",
  "interface",
  "module",
  "config"
];

export const DISPLAY_LEVEL_ICON_MAP: { [K in (typeof DISPLAY_LEVEL_LIST)[number]]: any } = {
  "all": { icon: "👁️", label: "Show All" },
  "component": { icon: "🎨", label: "Component" },
  "class": { icon: "☕", label: "Class" },
  "interface": { icon: "⚙️", label: "Interface" },
  "module": { icon: "📦", label: "Module" },
  "config": { icon: "🔧", label: "Configuration" },
} as const;

export type DisplayLevel = (typeof DISPLAY_LEVEL_LIST)[number];

export function isDisplayLevel(value: unknown): value is DisplayLevel {
  return typeof value === "string" && DISPLAY_LEVEL_LIST.includes(value);
}

export function getDisplayLevel(value: unknown): DisplayLevel | undefined {
  if (typeof value === "string" && DISPLAY_LEVEL_LIST.includes(value)) {
    return value as DisplayLevel;
  }
  return undefined;
}
