// Auto-generated by dev-tools/generate-types.js. DO NOT EDIT DIRECTLY.

export const MAXIMIZE_SCOPE_LIST: readonly string[] = [
  "Workspace",
  "Main"
];

export const MAXIMIZE_SCOPE_ICON_MAP: { [K in (typeof MAXIMIZE_SCOPE_LIST)[number]]: any } = {
  "Workspace": { icon: "🔲", label: "Workspace" },
  "Main": { icon: "🖥️", label: "Main" },
} as const;

export type MaximizeScope = (typeof MAXIMIZE_SCOPE_LIST)[number];

export function isMaximizeScope(value: unknown): value is MaximizeScope {
  return typeof value === "string" && MAXIMIZE_SCOPE_LIST.includes(value);
}

export function getMaximizeScope(value: unknown): MaximizeScope | undefined {
  if (typeof value === "string" && MAXIMIZE_SCOPE_LIST.includes(value)) {
    return value as MaximizeScope;
  }
  return undefined;
}
