// Auto-generated by dev-tools/generate-types.js. DO NOT EDIT DIRECTLY.

export const EXPORT_FORMAT_LIST: readonly string[] = [
  "yaml",
  "json",
  "toml",
  "xml",
  "txt"
];

export const EXPORT_FORMAT_ICON_MAP: { [K in (typeof EXPORT_FORMAT_LIST)[number]]: any } = {
  "yaml": { icon: "📄", label: "YAML" },
  "json": { icon: "🟦", label: "JSON" },
  "toml": { icon: "🟫", label: "TOML" },
  "xml": { icon: "🔤", label: "XML" },
  "txt": { icon: "📝", label: "TXT" },
} as const;

export type ExportFormat = (typeof EXPORT_FORMAT_LIST)[number];

export function isExportFormat(value: unknown): value is ExportFormat {
  return typeof value === "string" && EXPORT_FORMAT_LIST.includes(value);
}

export function getExportFormat(value: unknown): ExportFormat | undefined {
  if (typeof value === "string" && EXPORT_FORMAT_LIST.includes(value)) {
    return value as ExportFormat;
  }
  return undefined;
}
