// Auto-generated by dev-tools/generate-types.js. DO NOT EDIT DIRECTLY.

export const CODEBASE_GROUPING_LIST: readonly string[] = [
  "scope",
  "folder",
  "layer",
  "typology",
  "tags"
];

export const CODEBASE_GROUPING_ICON_MAP: { [K in (typeof CODEBASE_GROUPING_LIST)[number]]: any } = {
  "scope": { icon: "📄", label: "By Scope" },
  "folder": { icon: "📁", label: "By Folder" },
  "layer": { icon: "🏗️", label: "By Layer" },
  "typology": { icon: "🧩", label: "By Typology" },
  "tags": { icon: "🏷️", label: "By Tags" },
} as const;

export type CodebaseGrouping = (typeof CODEBASE_GROUPING_LIST)[number];

export function isCodebaseGrouping(value: unknown): value is CodebaseGrouping {
  return typeof value === "string" && CODEBASE_GROUPING_LIST.includes(value);
}

export function getCodebaseGrouping(value: unknown): CodebaseGrouping | undefined {
  if (typeof value === "string" && CODEBASE_GROUPING_LIST.includes(value)) {
    return value as CodebaseGrouping;
  }
  return undefined;
}
