const fs = require('fs');
const path = require('path');

const types_to_generate = [
  {
    name: 'DataScope',
    path: 'shared/services/graph-rag-explorer/types/type-data-scope.gen.ts',
    values: [
      { value: 'LOCAL_ONLY', label: 'Local Only', icon: '🏠' },
      { value: 'REMOTE_SYNC', label: 'Remote Sync', icon: '🌐' },
    ],
  },
];

function toMacroCase(str) {
  return str.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
}

function generateTypes() {
  const rootDir = path.resolve(__dirname, '..');

  types_to_generate.forEach((typeDef) => {
    const targetPath = path.resolve(rootDir, typeDef.path);
    const targetDir = path.dirname(targetPath);

    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }

    const typeName = typeDef.name;
    const macroName = toMacroCase(typeName);
    const listConstName = `${macroName}_LIST`;
    const iconMapConstName = `${macroName}_ICON_MAP`;
    const isGuardName = `is${typeName}`;
    const getFuncName = `get${typeName}`;

    const listValuesFormatted = JSON.stringify(typeDef.values.map((v) => v.value), null, 2);

    const iconMapEntries = typeDef.values
      .map((v) => `  ${v.value}: { icon: "${v.icon || ''}", label: "${v.label}" },`)
      .join('\n');

    const fileContent = `// Auto-generated by dev-tools/generate-types.js. DO NOT EDIT DIRECTLY.

export const ${listConstName}: readonly string[] = ${listValuesFormatted};

export const ${iconMapConstName}: { [K in (typeof ${listConstName})[number]]: any } = {
${iconMapEntries}
} as const;

export type ${typeName} = (typeof ${listConstName})[number];

export function ${isGuardName}(value: unknown): value is ${typeName} {
  return typeof value === "string" && ${listConstName}.includes(value);
}

export function ${getFuncName}(value: unknown): ${typeName} | undefined {
  if (typeof value === "string" && ${listConstName}.includes(value)) {
    return value as ${typeName};
  }
  return undefined;
}
`;

    fs.writeFileSync(targetPath, fileContent, 'utf-8');
    console.log(`[generate-types] Successfully generated: ${typeDef.path}`);
  });
}

generateTypes();
