const fs = require('fs');
const path = require('path');

const jsonPath = path.resolve(__dirname, 'generate-types.json');
if (!fs.existsSync(jsonPath)) {
  console.error(`❌ Configuration file not found at: ${jsonPath}`);
  process.exit(1);
}

const types_to_generate = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));

function toMacroCase(str) {
  return str.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
}

function generateTypes() {
  const rootDir = path.resolve(__dirname, '..');

  console.log(`------------------------------------------------------------------------`);
  console.log(`📦 [generate-types] Generate types from : "dev-tools/generate-types.json"`);

  types_to_generate.forEach((typeDef) => {
    const targetPath = path.resolve(rootDir, typeDef.path);
    const targetDir = path.dirname(targetPath);

    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }

    const typeName = typeDef.name;
    const macroName = toMacroCase(typeName);
    const listConstName = `${macroName}_LIST`;
    const iconMapConstName = `${macroName}_ICON_MAP`;
    const isGuardName = `is${typeName}`;
    const getFuncName = `get${typeName}`;

    const listValuesFormatted = JSON.stringify(typeDef.values.map((v) => v.value), null, 2);

    const iconMapEntries = typeDef.values
      .map((v) => `  ${JSON.stringify(v.value)}: { icon: "${v.icon || ''}", label: "${v.label}" },`)
      .join('\n');

    const fileContent = `// Auto-generated by dev-tools/generate-types.js. DO NOT EDIT DIRECTLY.

export const ${listConstName}: readonly string[] = ${listValuesFormatted};

export const ${iconMapConstName}: { [K in (typeof ${listConstName})[number]]: any } = {
${iconMapEntries}
} as const;

export type ${typeName} = (typeof ${listConstName})[number];

export function ${isGuardName}(value: unknown): value is ${typeName} {
  return typeof value === "string" && ${listConstName}.includes(value);
}

export function ${getFuncName}(value: unknown): ${typeName} | undefined {
  if (typeof value === "string" && ${listConstName}.includes(value)) {
    return value as ${typeName};
  }
  return undefined;
}
`;

    fs.writeFileSync(targetPath, fileContent, 'utf-8');
    console.log(`🟢 [generate-types] Successfully generated: ${typeDef.path}`);
  });
}

generateTypes();
