import { PaletteItemDefinition } from '../model-ui';

export const PALETTE_ITEMS: PaletteItemDefinition[] = [
  // --- DATA NODES ---
  {
    type: 'textInput',
    label: 'Text Input',
    group: 'Data Node',
    subGroup: 'Inputs',
    description: 'The starting prompt for the flow',
    iconName: 'Type',
  },
  {
    type: 'jsonInput',
    label: 'JSON Input',
    group: 'Data Node',
    subGroup: 'Inputs',
    description: 'Define raw or structured JSON payload in a textarea',
    iconName: 'FileJson',
  },
  {
    type: 'urlInput',
    label: 'URL Input',
    group: 'Data Node',
    subGroup: 'Inputs',
    description: 'HTTP/HTTPS URL endpoint request with Bearer Token authentication',
    iconName: 'Globe',
  },
  {
    type: 'markdownFile',
    label: 'Markdown File',
    group: 'Data Node',
    subGroup: 'Inputs',
    description: 'A Markdown instruction file for the flow',
    iconName: 'FileText',
  },
  {
    type: 'image',
    label: 'Image Node',
    group: 'Data Node',
    subGroup: 'Media & Assets',
    description: 'Display image or URL preview (https, http, file, data)',
    iconName: 'Image',
  },
  {
    type: 'formattedOutput',
    label: 'Formatted Output',
    group: 'Data Node',
    subGroup: 'Outputs',
    description: 'Renders the result as Markdown',
    iconName: 'LayoutTemplate',
  },
  {
    type: 'annotation',
    label: 'Annotation Note',
    group: 'Data Node',
    subGroup: 'Annotations',
    description: 'Movable setup notes box with dashed link',
    iconName: 'Info',
  },

  // --- STEP NODES ---
  {
    type: 'llm',
    label: 'LLM Node',
    group: 'Step Node',
    subGroup: 'AI & Models',
    description: 'Run LLMs (Ollama, Copilot, Gemini, Claude) with context files',
    iconName: 'Cpu',
    badge: 'Core',
  },
  {
    type: 'aiAgent',
    label: 'AI Agent',
    group: 'Step Node',
    subGroup: 'AI & Models',
    description: 'Runs an LLM with tool calling',
    iconName: 'Bot',
  },
  {
    type: 'replace',
    label: 'Replace Text',
    group: 'Step Node',
    subGroup: 'Transformers',
    description: 'Regex search pattern and replace string transformer',
    iconName: 'Replace',
  },
  {
    type: 'sanitize',
    label: 'Sanitize Text',
    group: 'Step Node',
    subGroup: 'Transformers',
    description: 'Mask, hash, or redact sensitive text pattern matches',
    iconName: 'ShieldCheck',
  },
  {
    type: 'extractData',
    label: 'Extract Variable',
    group: 'Step Node',
    subGroup: 'Extractors',
    description: 'Extract text using Regex pattern into a context variable',
    iconName: 'FileCode',
  },
  {
    type: 'script',
    label: 'Script Execution',
    group: 'Step Node',
    subGroup: 'Scripts & Code',
    description: 'Execute Python or Bash scripts with argument inputs',
    iconName: 'Terminal',
  },
  {
    type: 'argument',
    label: 'Script Argument',
    group: 'Step Node',
    subGroup: 'Scripts & Code',
    description: 'Key/Value input argument for script execution',
    iconName: 'Variable',
  },
  {
    type: 'outputAnalyzer',
    label: 'Output Analyzer',
    group: 'Step Node',
    subGroup: 'Logic',
    description: 'Evaluates workflow output with OK / KO branch endpoints',
    iconName: 'GitFork',
  },
  {
    type: 'searchTool',
    label: 'Search Reddit',
    group: 'Step Node',
    subGroup: 'Tools',
    description: 'Finds trending posts in a subreddit',
    iconName: 'Search',
  },
];
