// Auto-generated by dev-tools/generate-types.js. DO NOT EDIT DIRECTLY.

export const EDGE_ARROW_SHAPE_LIST: readonly string[] = [
  "triangle",
  "triangle-tee",
  "circle-triangle",
  "triangle-cross",
  "triangle-backcurve",
  "vee",
  "tee",
  "square",
  "circle",
  "diamond",
  "chevron",
  "none"
];

export const EDGE_ARROW_SHAPE_ICON_MAP: { [K in (typeof EDGE_ARROW_SHAPE_LIST)[number]]: any } = {
  "triangle": { icon: "", label: "Triangle" },
  "triangle-tee": { icon: "", label: "Triangle Tee" },
  "circle-triangle": { icon: "", label: "Circle Triangle" },
  "triangle-cross": { icon: "", label: "Triangle Cross" },
  "triangle-backcurve": { icon: "", label: "Triangle Backcurve" },
  "vee": { icon: "", label: "Vee" },
  "tee": { icon: "", label: "Tee" },
  "square": { icon: "", label: "Square" },
  "circle": { icon: "", label: "Circle" },
  "diamond": { icon: "", label: "Diamond" },
  "chevron": { icon: "", label: "Chevron" },
  "none": { icon: "", label: "None" },
} as const;

export type EdgeArrowShape = (typeof EDGE_ARROW_SHAPE_LIST)[number];

export function isEdgeArrowShape(value: unknown): value is EdgeArrowShape {
  return typeof value === "string" && EDGE_ARROW_SHAPE_LIST.includes(value);
}

export function getEdgeArrowShape(value: unknown): EdgeArrowShape | undefined {
  if (typeof value === "string" && EDGE_ARROW_SHAPE_LIST.includes(value)) {
    return value as EdgeArrowShape;
  }
  return undefined;
}
