// Auto-generated by dev-tools/generate-types.js. DO NOT EDIT DIRECTLY.

export const NODE_STATUS_LIST: readonly string[] = [
  "pending",
  "current",
  "completed",
  "cancelled"
];

export const NODE_STATUS_ICON_MAP: { [K in (typeof NODE_STATUS_LIST)[number]]: any } = {
  "pending": { icon: "", label: "Pending" },
  "current": { icon: "", label: "Current" },
  "completed": { icon: "", label: "Completed" },
  "cancelled": { icon: "", label: "Cancelled" },
} as const;

export type NodeStatus = (typeof NODE_STATUS_LIST)[number];

export function isNodeStatus(value: unknown): value is NodeStatus {
  return typeof value === "string" && NODE_STATUS_LIST.includes(value);
}

export function getNodeStatus(value: unknown): NodeStatus | undefined {
  if (typeof value === "string" && NODE_STATUS_LIST.includes(value)) {
    return value as NodeStatus;
  }
  return undefined;
}
