// Auto-generated by dev-tools/generate-types.js. DO NOT EDIT DIRECTLY.

export const EDGE_CURVE_STYLE_LIST: readonly string[] = [
  "haystack",
  "straight",
  "bezier",
  "unbundled-bezier",
  "segments",
  "taxi"
];

export const EDGE_CURVE_STYLE_ICON_MAP: { [K in (typeof EDGE_CURVE_STYLE_LIST)[number]]: any } = {
  "haystack": { icon: "", label: "Haystack" },
  "straight": { icon: "", label: "Straight" },
  "bezier": { icon: "", label: "Bezier" },
  "unbundled-bezier": { icon: "", label: "Unbundled Bezier" },
  "segments": { icon: "", label: "Segments" },
  "taxi": { icon: "", label: "Taxi" },
} as const;

export type EdgeCurveStyle = (typeof EDGE_CURVE_STYLE_LIST)[number];

export function isEdgeCurveStyle(value: unknown): value is EdgeCurveStyle {
  return typeof value === "string" && EDGE_CURVE_STYLE_LIST.includes(value);
}

export function getEdgeCurveStyle(value: unknown): EdgeCurveStyle | undefined {
  if (typeof value === "string" && EDGE_CURVE_STYLE_LIST.includes(value)) {
    return value as EdgeCurveStyle;
  }
  return undefined;
}
