// Auto-generated by dev-tools/generate-types.js. DO NOT EDIT DIRECTLY.

export const EDGE_LINE_STYLE_LIST: readonly string[] = [
  "solid",
  "dotted",
  "dashed"
];

export const EDGE_LINE_STYLE_ICON_MAP: { [K in (typeof EDGE_LINE_STYLE_LIST)[number]]: any } = {
  "solid": { icon: "", label: "Solid" },
  "dotted": { icon: "", label: "Dotted" },
  "dashed": { icon: "", label: "Dashed" },
} as const;

export type EdgeLineStyle = (typeof EDGE_LINE_STYLE_LIST)[number];

export function isEdgeLineStyle(value: unknown): value is EdgeLineStyle {
  return typeof value === "string" && EDGE_LINE_STYLE_LIST.includes(value);
}

export function getEdgeLineStyle(value: unknown): EdgeLineStyle | undefined {
  if (typeof value === "string" && EDGE_LINE_STYLE_LIST.includes(value)) {
    return value as EdgeLineStyle;
  }
  return undefined;
}
