// Auto-generated by dev-tools/generate-types.js. DO NOT EDIT DIRECTLY.

export const NODE_TYPE_LIST: readonly string[] = [
  "start",
  "end",
  "step",
  "decision"
];

export const NODE_TYPE_ICON_MAP: { [K in (typeof NODE_TYPE_LIST)[number]]: any } = {
  "start": { icon: "", label: "Start" },
  "end": { icon: "", label: "End" },
  "step": { icon: "", label: "Step" },
  "decision": { icon: "", label: "Decision" },
} as const;

export type NodeType = (typeof NODE_TYPE_LIST)[number];

export function isNodeType(value: unknown): value is NodeType {
  return typeof value === "string" && NODE_TYPE_LIST.includes(value);
}

export function getNodeType(value: unknown): NodeType | undefined {
  if (typeof value === "string" && NODE_TYPE_LIST.includes(value)) {
    return value as NodeType;
  }
  return undefined;
}
