// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Rebuild using: npm run generate:rpc-methods

export enum RpcMethodEnum {
    CODEBASEEXPORTER_EXPORT_SELECTED_FILES = 'exportSelectedFiles',
    CODEBASEEXPORTER_EXPORT_FILES = 'exportFiles',
    CODEBASEEXPORTER_GET_EXPORT_FILES_STATUS = 'getExportFilesStatus',
    CODEBASEEXPORTER_GET_EXPORT_FILES_RESULT = 'getExportFilesResult',
    CODEBASEEXPORTER_READ_EXPORTED_FILES_CONTENT = 'readExportedFilesContent',
    CODEBASEEXPORTER_STORE_EXPORTED_FILES_IN_CLIPBOARD = 'storeExportedFilesInClipboard',
    BLASTRADIUSERRORFILESIDENTIFICATOR_SEARCH_FILES = 'searchFiles',
    FILESYSTEM_EXISTS = 'exists',
    FILESYSTEM_IS_DIRECTORY = 'isDirectory',
    FILESYSTEM_CLEAR_DIRECTORY = 'clearDirectory',
    FILESYSTEM_GET_INVALID_PATHS = 'getInvalidPaths',
    FILESYSTEM_READ_FILE = 'readFile',
    GIT_GET_LOCAL_MODIFIED_FILES_FROM_LAST_COMMIT = 'getLocalModifiedFilesFromLastCommit',
    GIT_GET_LOCAL_MODIFIED_FILES_FROM_REMOTE_BRANCH = 'getLocalModifiedFilesFromRemoteBranch',
    GRAGEXPLORER_GET_PATHS_CHANGE_IMPACTS = 'getPathsChangeImpacts',
    GRAGINSTALLER_READ_INSTALLATION_REPORT = 'readInstallationReport',
    GRAGINSTALLER_UNINSTALL_ALL = 'uninstallAll',
    IMAGE_READ_IMAGE_AS_BASE64 = 'readImageAsBase64',
    LLMCHAT_EXECUTE_CHAT = 'executeChat',
    LLMCHAT_STREAM_CHAT = 'streamChat',
    LLMCHAT_LIST_AVAILABLE_MODELS = 'listAvailableModels',
    LLMCHAT_HEALTH_CHECK = 'healthCheck',
    LLMCHAT_READ_FILE_CONTENT = 'readFileContent',
    NEO4J_EXECUTE_CYPHER = 'executeCypher',
    NEO4J_START_NEO4J_DATABASE = 'startNeo4jDatabase',
    NEO4J_STOP_NEO4J_DATABASE = 'stopNeo4jDatabase',
    NEO4J_RESTART_NEO4J_DATABASE = 'restartNeo4jDatabase',
    REFERENCE_LOAD_ALL_REFERENCES = 'loadAllReferences',
    REFERENCE_SAVE = 'save',
    REFERENCE_UPDATE = 'update',
    REFERENCE_DELETE = 'delete',
    REFERENCE_READ_URL_CONTENT = 'readUrlContent',
    SDLCSESSION_SAVE_SESSION = 'saveSession',
    SDLCSESSION_LOAD_ALL_SESSIONS = 'loadAllSessions',
    SDLCSESSION_DELETE_SESSION = 'deleteSession',
    VSCODE_GET_REPO_NAME = 'getRepoName',
    VSCODE_GET_WORKSPACE_ROOT_PATH = 'getWorkspaceRootPath',
    VSCODE_LOG_MESSAGE = 'logMessage',
    VSCODE_GET_EXTENSION_SETTINGS = 'getExtensionSettings',
    VSCODE_OPEN_URL = 'openUrl',
    VSCODE_OPEN_FILE = 'openFile',
    VSCODE_REVEAL_IN_EXPLORER = 'revealInExplorer',
    VSCODE_COPY_TO_CLIPBOARD = 'copyToClipboard',
    VSCODE_SAVE_USER_PREFERENCES = 'saveUserPreferences',
    VSCODE_READ_USER_PREFERENCES = 'readUserPreferences'
}
