export const VSCODE_COMMANDS = {
    EXPORTER_CODEBASE_ADD_PATHS: 'exporterCodebaseAddPaths',
    EXPORTER_CODEBASE_EXCLUDE_PATHS: 'exporterCodebaseExcludePaths',
    EXPORTER_REFERENCE_ADD_PATHS: 'exporterReferenceAddPaths',
    EXPORTER_REFERENCE_EXCLUDE_PATHS: 'exporterReferenceExcludePaths',
    EXPLORER_ADD_PATHS: 'explorerAddPaths',
} as const;

export type VsCodeCommand = typeof VSCODE_COMMANDS[keyof typeof VSCODE_COMMANDS];

// Also export individual constants for direct usage
export const EXPORTER_CODEBASE_ADD_PATHS = VSCODE_COMMANDS.EXPORTER_CODEBASE_ADD_PATHS;
export const EXPORTER_CODEBASE_EXCLUDE_PATHS = VSCODE_COMMANDS.EXPORTER_CODEBASE_EXCLUDE_PATHS;
export const EXPORTER_REFERENCE_ADD_PATHS = VSCODE_COMMANDS.EXPORTER_REFERENCE_ADD_PATHS;
export const EXPORTER_REFERENCE_EXCLUDE_PATHS = VSCODE_COMMANDS.EXPORTER_REFERENCE_EXCLUDE_PATHS;
export const EXPLORER_ADD_PATHS = VSCODE_COMMANDS.EXPLORER_ADD_PATHS;
