// Auto-generated by dev-tools/generate-types.js. DO NOT EDIT DIRECTLY.

export const SEARCH_MATCH_LIST: readonly string[] = [
  "contains",
  "start-with",
  "end-with"
];

export const SEARCH_MATCH_ICON_MAP: { [K in (typeof SEARCH_MATCH_LIST)[number]]: any } = {
  "contains": { icon: "", label: "Contains" },
  "start-with": { icon: "", label: "Start With" },
  "end-with": { icon: "", label: "End With" },
} as const;

export type SearchMatch = (typeof SEARCH_MATCH_LIST)[number];

export function isSearchMatch(value: unknown): value is SearchMatch {
  return typeof value === "string" && SEARCH_MATCH_LIST.includes(value);
}

export function getSearchMatch(value: unknown): SearchMatch | undefined {
  if (typeof value === "string" && SEARCH_MATCH_LIST.includes(value)) {
    return value as SearchMatch;
  }
  return undefined;
}
