// Auto-generated by dev-tools/generate-types.js. DO NOT EDIT DIRECTLY.

export const FINDER_VIEW_LIST: readonly string[] = [
  "toolbar",
  "bubble"
];

export const FINDER_VIEW_ICON_MAP: { [K in (typeof FINDER_VIEW_LIST)[number]]: any } = {
  "toolbar": { icon: "", label: "Toolbar" },
  "bubble": { icon: "", label: "Bubble" },
} as const;

export type FinderView = (typeof FINDER_VIEW_LIST)[number];

export function isFinderView(value: unknown): value is FinderView {
  return typeof value === "string" && FINDER_VIEW_LIST.includes(value);
}

export function getFinderView(value: unknown): FinderView | undefined {
  if (typeof value === "string" && FINDER_VIEW_LIST.includes(value)) {
    return value as FinderView;
  }
  return undefined;
}
