// Auto-generated by dev-tools/generate-types.js. DO NOT EDIT DIRECTLY.

export const SEARCH_BY_LIST: readonly string[] = [
  "name",
  "tags",
  "both"
];

export const SEARCH_BY_ICON_MAP: { [K in (typeof SEARCH_BY_LIST)[number]]: any } = {
  "name": { icon: "", label: "Name" },
  "tags": { icon: "", label: "Tags" },
  "both": { icon: "", label: "Both" },
} as const;

export type SearchBy = (typeof SEARCH_BY_LIST)[number];

export function isSearchBy(value: unknown): value is SearchBy {
  return typeof value === "string" && SEARCH_BY_LIST.includes(value);
}

export function getSearchBy(value: unknown): SearchBy | undefined {
  if (typeof value === "string" && SEARCH_BY_LIST.includes(value)) {
    return value as SearchBy;
  }
  return undefined;
}
